language: python
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - secure: AE6SVLz7QMjCyG4EPkmBiviDTZ64Rzer0IaIlR1rgASl5z1PWSGh+iCBQYQFnN9kVakeVFnszEB/bDtLboOAG3tEKmDzyjhn81j8twxFd5Tzr96gnLalExLZwFFZIWpYoz86DrxfhK7e04RdqsqArCmhEIZb7W4vnmMCvK5L27o=
    - secure: GyEUv+x3iGwuN9qtetWzv71bVkuPvRSN5+eMukAZYt51q6lTxkRD1KsSVqLz7NC5AcdahwZL6Js5puQSSa0ilrJrEnySRpHso3Sk7J8Oy9U6H1UuGK7USQA5LT6eMuyX7Fo5fHXJPKkitOTvAlarHA14tSXZ58zYENgwnAqRC7E=
  - python: 3.2
    env:
    - NUMPYSPEC===1.8.0
  - python: 3.3
    env:
    - NUMPYSPEC===1.8.0
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev
- if [ -n "${NUMPYSPEC}" ]; then sudo apt-get install -qq gfortran; fi
- if [ -n "${NUMPYSPEC}" ]; then pip install --upgrade pip setuptools; fi
- if [ -n "${NUMPYSPEC}" ]; then pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel numpy$NUMPYSPEC matplotlib sphinx nose; fi
- pip install coveralls
install:
- python bootstrap.py
- ./bin/buildout
script:
- ./bin/python -c 'from bob.db.verification.utils import get_config; print(get_config())'
- ./bin/coverage run --source=bob.db.verification.utils ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- ./src/bob.extension/scripts/upload-sphinx.sh
